# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html
version: "2"
mkdocs:
  configuration: "mkdocs.yml"
python:
  version: "3.12"
  install:
    - method: "pip"
      path: "."
      extra_requirements:
        - "dev"
