# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html
version: "2"
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"
mkdocs:
  configuration: "mkdocs-rtd.yml"
python:
  install:
    - requirements: docs/requirements.txt
    - method: "pip"
      path: "."
