language: python
python:
- 2.7
- 3.3
- 3.4
- pypy
sudo: false
install:
- pip install -r requirements.txt -r test-requirements.txt
script:
- nosetests
deploy:
  provider: pypi
  user: daveshawley
  password:
    secure: U5mCjNIqm8nnEQTLu+UU4tGnNhMnNjWlUcK+tUBo8ZqStq+bCiwg1hwxywMtWPEAhbuEx9U5rGbsF/MkW4JGcct0hcmOQBLjj5IcS8hiueS5WnV/p/pCG5llhFmhZi7KJxgiGjNrgFEuZ/D5ULYq/n7zCsDOmYEcHSs6XhGfr00=
  distributions: sdist bdist_wheel
  on:
    tags: true
    all_branches: true
    repo: dave-shawley/ietfparse
    python: 3.4
