language: python
python:
- 2.7
- 3.3
- 3.4
- pypy
install:
- pip install -r requirements.txt -r test-requirements.txt
script:
- nosetests
deploy:
  provider: pypi
  user: daveshawley
  password:
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    all_branches: true
    repo: dave-shawley/ietfparse
    python: 3.4
