[project]
name = "ietfparse"
dynamic = ["version"]
description = "Parse formats defined in IETF RFCs"
readme = "README.rst"
requires-python = ">=3.9"
license = { file = "LICENSE" }
authors = [ { name = "Dave Shawley", email = "daveshawley@gmail.com" } ]
classifiers = [
	"Intended Audience :: Developers",
	"License :: OSI Approved :: BSD License",
	"Operating System :: OS Independent",
	"Programming Language :: Python",
	"Programming Language :: Python :: 3",
	"Programming Language :: Python :: 3.9",
	"Programming Language :: Python :: 3.10",
	"Programming Language :: Python :: 3.11",
	"Programming Language :: Python :: 3.12",
	"Programming Language :: Python :: 3.13",
	"Development Status :: 5 - Production/Stable",
	"Environment :: Web Environment",
	"Topic :: Internet :: WWW/HTTP",
	"Topic :: Text Processing",
	"Typing :: Typed"
]

[project.urls]
Documentation = "https://ietfparse.readthedocs.io/"
"Source Code" = "https://github.com/dave-shawley/ietfparse"
"Code Coverage" = "https://coveralls.io/github/dave-shawley/ietfparse"
Maintainability = "https://codeclimate.com/github/dave-shawley/ietfparse/"

[project.optional-dependencies]
dev = [
	"coverage[toml]==5.5",
	"mypy==0.910",
	"pytest==7.1.2",
	"ruff==0.6.9",
	"sphinx==5.0.2",
	"sphinxcontrib-httpdomain==1.8.0",
	"sphinx-autodoc-typehints==1.18.3",
	"sphinx-material==0.0.35",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "ietfparse/__init__.py"
pattern = "version = '(?P<version>[^']*)'"

[tool.hatch.build.targets.sdist]
include = [
	"/.circleci",
	"/docs",
	"/ietfparse",
	"/tests",
	"/.codeclimate.yml",
	"/.readthedocs.yml",
	"/AUTHORS.rst",
	"/CONTRIBUTING.rst",
	"/sonar-project.properties",
]

[tool.hatch.envs.default]
features = ["dev"]
python = "3.12"

[tool.hatch.envs.default.scripts]
build-docs = [
	"sphinx-build docs build/sphinx/html -aEW"
]
coverage = [
	"python -m coverage run -m pytest tests",
	"python -m coverage report"
]
lint = [
	"ruff format",
	"ruff check",
	"mypy --strict --package ietfparse",
]
test = [
	"python -m unittest discover -f tests"
]

[[tool.hatch.envs.all.matrix]]
python = ["39", "310", "311", "312", "313"]

[tool.coverage.report]
show_missing = true

[tool.coverage.run]
branch = true
source = ["ietfparse"]

[tool.ruff]
line-length = 79

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
	"ANN",  # TODO -- temporarily ignoring these

	"COM812",	# conflicts with ruff formatter
	"D104",		# No need for docstring at the package level
	"D105",		# No need for docstrings in magic methods
	"D107",		# __init__ params are in the class docstring
	"D203",		# No blank lines before class docstring
	"D213",		# Start multiline docstrings on the second line
	"ISC001",	# conflicts with ruff formatter
	"N818",		# Exception class names don't end in "Error"
	"PT",   	# I don't like pytest conventions
	"EM101",	# Passing literal messages in raise is fine
	"EM102",	# Passing f-strings in raise is fine
	"TRY003",	# Passing literal messages in raise is fine
]
exclude = ["docs/conf.py"]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
	"D",    	# tests don't require docs
]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"
