sonar.organization=dave-shawley-github
sonar.projectKey=dave-shawley-github_ietfparse
sonar.projectName=ietfparse
sonar.links.ci=https://github.com/dave-shawley/ietfparse/actions/workflows/test.yml
sonar.links.homepage=https://ietfparse.readthedocs.io/en/latest/index.html
sonar.links.scm=https://github.com/dave-shawley/ietfparse
sonar.sources=src/ietfparse
sonar.tests=tests
sonar.python.version=3.10
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=junit.xml
